### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by amacneil** [foxglove/rosbag2-node#1]
Readme doesn't have any examples

**Comment by defunctzombie** [comment]
@esthersweon ping on this

**Comment by esthersweon** [comment]
Spoke with @jhurliman: "don't think these projects have any usage outside of studio... we don't want anyone to use them if possible, since they promote a file format we're actively working to kill off... say this is the (web/node.js) implementation of reading ROS 2 sqlite files, it's used in Studio for support of this legacy file format, and this format has been superseded by MCAP which you can read about here"

Based on this feedback, will revise README to do the following: 
- Clarify the purpose of repo / clean up empty or dead sections
- Mention usage in Foxglove Studio
- Point people towards MCAP
